### ISSUE TITLE
src/lib/disposableMailDomain.ts

### ISSUE THREAD

**Issue by chinapage** [serverless-domain-registry/registry#2]
china this is my personal email address, not a disposable email address.

**Comment by serverless-domain-registry** [comment]
Welcome to PR

**Comment by chinapage** [comment]
> Welcome to PR

这不是一个临时一次性邮箱 - -!

![mail](https://pic.rett.eu.org/logo/bbs/gh/lsmail.png)

**Comment by serverless-domain-registry** [comment]
closed in https://github.com/serverless-domain-registry/registry/commit/c0c5d2820ab1e9d2d36cd39a1d133bdfa558626b

**Comment by serverless-domain-registry** [comment]
The src/lib/disposableMailDomain.ts is a orphan file never been imported in any file at the previously version:
https://github.com/serverless-domain-registry/registry/tree/a9e69b92f75377d130b7c777aca9364372495d2f

And removed in https://github.com/serverless-domain-registry/registry/commit/c0c5d2820ab1e9d2d36cd39a1d133bdfa558626b

Sorry for our mistakes.
